name: smartpresence
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Pacote que faltava (para pt_BR)
  flutter_localizations:
    sdk: flutter

  # Comunicação WebSocket
  web_socket_channel: ^2.4.5 
  
  # Descoberta de Rede Local (NSD / mDNS)
  nsd: ^4.0.3

  # Salvar configurações de horário do professor
  shared_preferences: ^2.2.3
  
  # Para formatar datas e horas
  intl: ^0.20.2

  network_info_plus: ^5.0.3

  logging: ^1.2.0

  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
