name: smartpresence
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  web_socket_channel: ^2.4.5 
  
  nsd: ^4.0.3

  shared_preferences: ^2.2.3
  
  intl: ^0.20.2

  network_info_plus: ^5.0.3

  logging: ^1.2.0

  google_fonts: ^6.2.1
  
  permission_handler: ^11.3.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#4A00E0"